/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:f89a96cf-3be8-468a-a3e0-60246c847a1d",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_CgpvkabDO",
    "aws_user_pools_web_client_id": "3005al3c1ehbagiqqtmju7a611",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cbozmb4o2vbfjh3lpncrfrvpja.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
